[tool.poetry]
name = "sarc"
version = "0.1.0"
description = "Surveillance et analyse des ressources de calcul"
authors = ["Mila-IDT"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
fabric = "^3.0.0"

[tool.poetry.group.dev.dependencies]
black = ">= 22.12.0"
pylint = ">= 2.15.10"
isort = ">= 5.11.4"
mypy = ">= 0.991"
pytest = ">= 7.2.1"
pytest-cov = ">= 4.0.0"
pytest-regressions = ">= 2.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint]

[tool.isort]
